In [6]:
import torch
import numpy as np

In [29]:
def printw(*list):
    print(list, end="\n\n")

# Tensor 생성

### Scalar

In [3]:
t1 = torch.tensor(5)
print(t1.numel())

1


### Array - Like

In [4]:
temp_tuple = (1,2,3,4,5)
torch.tensor(temp_tuple)

tensor([1, 2, 3, 4, 5])

In [7]:
temp_numpy = np.array(temp_tuple)
torch.tensor(temp_numpy)
torch.from_numpy(temp_numpy)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

### Function

In [ ]:
torch.ones([3,3,3]) # 3 차원

In [ ]:
torch.zeros([3,3,3]) # 3 차원

In [ ]:
torch.arange(22,10,-1)

In [ ]:
torch.rand([5,5])

In [ ]:
zero = torch.zeros([2,3,4])
print(zero)

torch.ones_like(zero)

# Attribute

### Shape

In [14]:
t = torch.ones([2,3,4])
t.shape
#>>> [2,3,4]

torch.Size([2, 3, 4])

### dtype

In [15]:
t = torch.ones([2,3,4])
t.dtype
#>>> torch.float

torch.float32

### device

In [16]:
t = torch.ones([2,3,4])
t.device

device(type='cpu')

In [17]:
torch.cuda.is_available()

True

In [18]:
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 4090'

In [19]:
torch.cuda.device_count()

1

In [20]:
t1 = t.cuda()
t1.device

device(type='cuda', index=0)

# operation

### Element-wise

In [ ]:
t1 = torch.tensor([[2,4],[6,8]], dtype = torch.float)
t2 = torch.ones([2,2], dtype = torch.float) * 2

print(t1)
print(t2)

In [ ]:
print(t1 + t2) #t1.add(t2)
print(t1 - t2) #t1.sub(t2)
print(t1 * t2) #t1.mul(t2)
print(t1 / t2) #t1.div(t2)

In [ ]:
t1 += t2
print(t1)

### Reduction

In [ ]:
t = torch.rand([2,2])

printw(t)
printw(t.min())
printw(t.min(dim=0))
printw(t.min(dim=1))

In [37]:
print(t1.mean())
print(t1.mean(dim=0))
print(t1.mean(dim=1))

tensor(5.)
tensor([4., 6.])
tensor([3., 7.])


# Indexing

In [39]:
t = torch.rand([3,3])

printw(t)
printw(t[0][1])
printw(t[:,1:3])

(tensor([[0.7928, 0.0989, 0.8879],
        [0.1088, 0.2179, 0.8753],
        [0.6840, 0.1845, 0.0458]]),)

(tensor(0.0989),)

(tensor([[0.0989, 0.8879],
        [0.2179, 0.8753],
        [0.1845, 0.0458]]),)



# Shaping Operation

In [ ]:
t = torch.rand([2,4])
printw(t)
printw(t.reshape([4,2]))
printw(t.reshape([4,2,1]))
printw(t.reshape([8]))

In [ ]:
t = torch.rand([1,3,1,3])

printw(t.shape)
printw(t.squeeze())
printw(t)
printw(t.squeeze().shape)
printw(t.squeeze(dim=2).shape)
printw(t.squeeze(dim=1).shape)

In [ ]:
t = torch.rand([3,4])

print(t.shape)
print(t.unsqueeze(dim=0).shape)
print(t.unsqueeze(dim=1).shape)
print(t.unsqueeze(dim=2).shape)

In [ ]:
t1 = torch.rand([5, 24, 50])
t2 = torch.rand([5, 24, 50])

print(torch.cat([t1,t2], dim=0).shape) # [5+5, 24, 50]
print(torch.cat([t1,t2], dim=1).shape) # [5, 24+24, 50]
print(torch.cat([t1,t2], dim=2).shape) # [5, 24, 50+50]

In [54]:
t1 = torch.rand([5, 24, 50])
t2 = torch.rand([5, 24, 50])

print(torch.stack([t1,t2], dim=0).shape)
print(torch.stack([t1,t2], dim=1).shape)

torch.Size([2, 5, 24, 50])
torch.Size([5, 2, 24, 50])
